Fix the issue with secrets

diff --git a/.github/workflows/gitops-promotion-trigger.yaml b/.github/workflows/gitops-promotion-trigger.yaml
--- a/.github/workflows/gitops-promotion-trigger.yaml
+++ b/.github/workflows/gitops-promotion-trigger.yaml
@@ -5,15 +5,11 @@ name: GitOps Promotion Forwarder
 
 on:
   workflow_call:
-    # Defining these here allows them to be mapped correctly
-    # when using 'inherit' or explicit passing.
     secrets:
-      TEST_SECRET:
-        required: false
       API_KEY:
-        required: false
+        required: true
       GITOPS_PROMOTER_WEBHOOK_SECRET:
-        required: false
+        required: true
 jobs:
   forward-to-cloudbuild:
     runs-on: ubuntu-latest
@@ -29,18 +25,16 @@ jobs:
         env:
           SECRET_TEST: ${{ secrets.TEST_SECRET }}
         run: |
-          echo "$SECRET_TEST something something"
-          if [ -z "${SECRET_TEST}" ]; then echo "::error::Something is off with secrets"; exit 1; else echo "allgood" ; fi
-          #if [ -z "${{ secrets.API_KEY }}" ]; then echo "::error::secret API_KEY missing"; exit 1; fi
-          #if [ -z "${{ secrets.GITOPS_PROMOTER_WEBHOOK_SECRET }}" ]; then echo "::error::secret GITOPS_PROMOTER_WEBHOOK_SECRET missing"; exit 1; fi
-          #curl -X POST -H "Content-type: application/json" "https://cloudbuild.googleapis.com/v1/projects/sit-smp-cicd-8xr1/triggers/gitops-promoter-trigger:webhook?key=${{ secrets.API_KEY }}&secret=${{ secrets.GITOPS_PROMOTER_WEBHOOK_SECRET }}&trigger=gitops-promoter-trigger&projectId=sit-smp-cicd-8xr1" \
-          #  -H "Content-Type: application/json" \
-          #  -d '{
-          #    "branchName": "main",
-          #    "substitutions": {
-          #      "pr_number": "13",
-          #      "repo_name": "${{ github.repository }}",
-          #      "target_name": "${{ steps.parse.outputs.target_env }}",
-          #      "target_version": ""
-          #    }
-          #  }'
+          if [ -z "${{ secrets.API_KEY }}" ]; then echo "::error::secret API_KEY missing"; exit 1; fi
+          if [ -z "${{ secrets.GITOPS_PROMOTER_WEBHOOK_SECRET }}" ]; then echo "::error::secret GITOPS_PROMOTER_WEBHOOK_SECRET missing"; exit 1; fi
+          curl -X POST -H "Content-type: application/json" "https://cloudbuild.googleapis.com/v1/projects/sit-smp-cicd-8xr1/triggers/gitops-promoter-trigger:webhook?key=${{ secrets.API_KEY }}&secret=${{ secrets.GITOPS_PROMOTER_WEBHOOK_SECRET }}&trigger=gitops-promoter-trigger&projectId=sit-smp-cicd-8xr1" \
+            -H "Content-Type: application/json" \
+            -d '{
+              "branchName": "main",
+              "substitutions": {
+                "pr_number": "13",
+                "repo_name": "${{ github.repository }}",
+                "target_name": "${{ steps.parse.outputs.target_env }}",
+                "target_version": ""
+              }
+            }'
