[SMPCP-997] Check how dumb gh actions are IV

diff --git a/.github/workflows/gitops-promotion-trigger.yaml b/.github/workflows/gitops-promotion-trigger.yaml
--- a/.github/workflows/gitops-promotion-trigger.yaml
+++ b/.github/workflows/gitops-promotion-trigger.yaml
@@ -22,7 +22,8 @@ jobs:
         env:
           SECRET_TEST: ${{ secrets.TEST_SECRET }}
         run: |
-          echo $SECRET_TEST
+          echo "${SECRET_TEST}"
+          if [ -z "${SECRET_TEST}" ]; then echo "::error::Something is off with secrets"; exit 1; fi
           if [ -z "${{ secrets.API_KEY }}" ]; then echo "::error::secret API_KEY missing"; exit 1; fi
           if [ -z "${{ secrets.GITOPS_PROMOTER_WEBHOOK_SECRET }}" ]; then echo "::error::secret GITOPS_PROMOTER_WEBHOOK_SECRET missing"; exit 1; fi
           curl -X POST -H "Content-type: application/json" "https://cloudbuild.googleapis.com/v1/projects/sit-smp-cicd-8xr1/triggers/gitops-promoter-trigger:webhook?key=${{ secrets.API_KEY }}&secret=${{ secrets.GITOPS_PROMOTER_WEBHOOK_SECRET }}&trigger=gitops-promoter-trigger&projectId=sit-smp-cicd-8xr1" \
