[SMPCP-997] Check Secret existence

diff --git a/.github/workflows/gitops-promotion-trigger.yaml b/.github/workflows/gitops-promotion-trigger.yaml
--- a/.github/workflows/gitops-promotion-trigger.yaml
+++ b/.github/workflows/gitops-promotion-trigger.yaml
@@ -19,8 +19,8 @@ jobs:
 
       - name: Fire Cloud Build Webhook
         run: |
-          if [ -z "${{ secrets.API_KEY }}" ]; then echo "API_KEY missing"; exit 1; fi
-          if [ -z "${{ secrets.GITOPS_PROMOTER_WEBHOOK_SECRET }}" ]; then echo "GITOPS_PROMOTER_WEBHOOK_SECRET missing"; exit 1; fi
+          if [ -z "${{ secrets.API_KEY }}" ]; then echo "::error::secret API_KEY missing"; exit 1; fi
+          if [ -z "${{ secrets.GITOPS_PROMOTER_WEBHOOK_SECRET }}" ]; then echo "::error::secret GITOPS_PROMOTER_WEBHOOK_SECRET missing"; exit 1; fi
           curl -X POST -H "Content-type: application/json" "https://cloudbuild.googleapis.com/v1/projects/sit-smp-cicd-8xr1/triggers/gitops-promoter-trigger:webhook?key=${{ secrets.API_KEY }}&secret=${{ secrets.GITOPS_PROMOTER_WEBHOOK_SECRET }}&trigger=gitops-promoter-trigger&projectId=sit-smp-cicd-8xr1" \
             -H "Content-Type: application/json" \
             -d '{
